[package]
name = "rustl-sdr"
version = "0.2.0"
authors = ["Yuval Adam <_@yuv.al>"]

[dependencies]
rusb = "0.8"

[lib]
name = "rustl_sdr"
path = "src/lib.rs"

[[bin]]
name = "rustl_fm"
path = "src/rustl_fm.rs"
